# ==========================================
# Apache Flink Configuration
# ==========================================

global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/flink
  tag: 2.1.0-debian-12-r1

jobmanager:
  replicaCount: 1

  resources:
    requests:
      cpu: 50m
      memory: 200Mi

    limits:
      cpu: 1000m
      memory: 2Gi

taskmanager:
  replicaCount: 2

  resources:
    requests:
      cpu: 50m
      memory: 200Mi

    limits:
      cpu: 1000m
      memory: 2Gi

service:
  type: ClusterIP

ingress:
  enabled: false
