# Number of Kafka brokers
replicaCount: 3

image:
  registry: docker.io
  repository: bitnamilegacy/kafka
  tag: 4.0.0-debian-12-r10

listeners:
  client:
    protocol: PLAINTEXT

controller:
  replicaCount: 3
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  tolerations:
    - key: "node.kubernetes.io/memory-pressure"
      operator: "Exists"
      effect: "NoSchedule"

kraft:
  enabled: true

zookeeper:
  enabled: false

persistence:
  enabled: true
  storageClass: standard-rwo
  size: 20Gi

service:
  type: ClusterIP

externalAccess:
  enabled: false